### ISSUE TITLE
Runtime login

### ISSUE THREAD

**Issue by csnewman** [ed-cooper/lecture-hoarder#7]
It is quite a risk having raw passwords on disk. On each run the program should ask you for your username and password.

**Comment by ed-cooper** [comment]
An ideal solution would be a hybrid input - if `settings.py` already specifies a username and password, then use those, otherwise ask for it via std in.

The reason for storing the username and password inside `settings.py` was so that the program could be ran regularly (e.g. once a week) as a cron job, keeping your local copy of lecture podcasts up to date.

**Comment by ed-cooper** [comment]
Do you want to do this?
